<?php
    $carrier = $this->getMethodInstance();
    $formCode = $this->getFormCode();
    $rate_id = 'notime_notime';
    $zipInputId = 'gls_zip_input_'.$formCode;
    $priceTemplate = Mage::helper('core')->currency(0, true, false); //template of price with currency
    $matches = array();
    preg_match('/[\.,\,]/', $priceTemplate, $matches);
    $priceSeparator = $matches[0];
?>

<ul class="form-list" id="<?php echo $formCode ?>">
    <li>
        <span id="notime_shipment_additional_text"><?php echo $this->getAdditionalText(); ?></span>
    </li>
    <input type="hidden" id="<?php echo $this->getWidgetZipCode();?>" name="magento_notime_zip_code" value="<?php echo $this->getQuote()->getShippingAddress()->getPostcode();?>">
    <input type="hidden" id="notime_shipment_id" name="notime_shipment_id" class="input-text required-notime-shipment" value="-">
    <input type="hidden" id="notime_shipment_fee" name="notime_shipment_fee" class="input-text" value="">
	<input type="hidden" id="notime_confirmed_time_window_description" name="notime_confirmed_time_window_description" class="input-text" value="">
    <li>
        <?php echo $this->getWidgetButton(); ?>
        <span id="notime_shipment_success"></span>
    </li>
    <script type="text/javascript">
	// <![CDATA[
		function getShippingPriceLabel(){
			return $$("label[for='s_method_notime_notime'] span[class='price']")[0];
		}
        
        function updateShippingPriceLabel(fee){
			var priceLabel = getShippingPriceLabel();
			if (fee !== ''){
				var feeStr = fee.toString().replace(/[\.,\,]/g, '<?php echo $priceSeparator; ?>');
				var priceStr = '<?php echo $priceTemplate; ?>'.replace(/\d+([\.,\,]\d{1,2})?/gi, feeStr);
				priceLabel.update(priceStr); 
			}
			else{
				priceLabel.update(""); 
			}
        }
		
        var shipmentGeneratedHandler = function(event) {
            var generatedId = event.detail.generatedShippmentGuid;
            var shipmentFee = event.detail.fee;
			var confirmedTimeWindowDescription = event.detail.selectedTimeWindowDescription;
            if(generatedId) {
                $('notime_shipment_id').setValue(generatedId);
                $('notime_shipment_fee').setValue(shipmentFee);
				$('notime_confirmed_time_window_description').setValue(confirmedTimeWindowDescription);
				updateShippingPriceLabel(shipmentFee);
                var $validationError = $('advice-required-notime-shipment-notime_shipment_id');
                if($validationError){
                    $validationError.hide();
                }
                $('notime_shipment_success').update('<?php echo $this->__('You have successfully selected time window'); ?>');
            }
        }
		
		var timeWindowConfirmedHandler = function(event){
			$('notime_shipment_id').setValue('-'); //Default value unless shipmentId have generated yet.
			$('notime_shipment_success').update('');
		}
		
        document.body.addEventListener("notime_widget:shipmentGenerated",shipmentGeneratedHandler);
		document.body.addEventListener("notime_widget:timeWindowConfirmed",timeWindowConfirmedHandler);

        function load_js() {
            var head= document.getElementsByTagName('head')[0];
            var script= document.createElement('script');
            script.type= 'text/javascript';
            script.src= '<?php echo $this->getWidgetCodeSrc(); ?>';
            head.appendChild(script);
        }
        load_js();

        document.observe('dom:loaded', function(){
            createNotimeShippingForm<?php echo $formCode ?>();
        });

        createNotimeShippingForm<?php echo $formCode ?>();

        function createNotimeShippingForm<?php echo $formCode ?>(){
            new NotimeShippingForm('<?php echo $rate_id; ?>','<?php echo $formCode; ?>');
        }
        
         Translator.add('Click here and choose your delivery time-slot','<?php echo Mage::helper('notimeshipping')->__('Click here and choose your delivery time-slot')?>');
		 updateShippingPriceLabel('');
    // ]]>
    </script>
</ul>
